# Please see the documentation for all configuration options if needed:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "yuiop/portal" 
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "nuget"
    directory: "yuiop/core" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "dotnet-sdk"
    directory: "yuiop/core" 
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
