name: Generate Client

on:
  pull_request:
    types:
    - opened
    - synchronize

jobs:
  generate-client:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.FULL_STACK_FASTAPI_TEMPLATE_REPO_TOKEN }}
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "0.4.15"
        enable-cache: true
    - name: Install dependencies
      run: npm ci
      working-directory: portal
    - run: uv sync
      working-directory: core
    - run: uv run bash scripts/generate-client.sh
      env:
        VIRTUAL_ENV: core/.venv
    - name: Commit changes
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "github-actions"
        git add portal/src/client
        git diff --staged --quiet || git commit -m "✨ Autogenerate portal client"
        git push
